//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.15 at 05:04:24 PM MSK 
//


package src.phonebook.contact.xml;

import src.phonebook.contact.AbstractPhoneNumber;
import src.phonebook.contact.PhoneBookFactory;
import src.phonebook.contact.PhoneBook;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numberID",
    "phoneNumber",
    "description"
})
@XmlRootElement(name = "phoneNumber")
public class PhoneNumber extends AbstractPhoneNumber {

    private int numberID;
    @XmlElement(required = true)
    private String phoneNumber;
    @XmlElement(required = true)
    private String description;

    int getNumberID() {
        return numberID;
    }

    public PhoneNumber() {}

    public PhoneNumber(int id, String number, String description) {
        numberID = id;
        phoneNumber = number;
        this.description = description;
    }


    @Override
    public String getDescription() {
        return description;
    }

    @Override
    public void setDescription(String value) {
        this.description = value;
        saveChanges();
    }


    @Override
    public int getId() {
        return getNumberID();
    }

    @Override
    public String getNumber() {
        return phoneNumber;
    }

    @Override
    public void setNumber(String number) {
        this.phoneNumber =number;
        saveChanges();
    }

    //Сохранение изменеий в файл.
    private void saveChanges() {
        PhoneBook phoneBook = PhoneBookFactory.getPhoneBook();

        if(phoneBook instanceof src.phonebook.contact.xml.PhoneBook)
            XMLSaveLoader.savePhoneBook(PhoneBookFactory.getPhoneBook());
    }
}
